task:
  type: inference_validation

mc: 340StringMC
geometry: 160_string_emax1e6
router_name: router2

base_inference_config: /project/def-nahee/kbas/graphnet/examples/08_pone/configs/inference/160_string_emax1e6__category2_tauCC_others_muonCC.yml

output:
  root_dir: /project/def-nahee/kbas/Graphnet-Applications/Results
  filename: router2_predictions.csv

run:
  existing_output: error

slurm:
  account: def-nahee
  time: "01:00:00"
  mem: 96G
  cpus_per_task: 8
  gpus_per_node: nvidia_h100_80gb_hbm3_3g.40gb:1
  exclude: fc10713
